# Generated by Django 5.2.3 on 2025-06-12 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pr_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_no', models.CharField(max_length=100, unique=True)),
                ('rfo_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pr_date', models.DateTimeField()),
                ('pr_documents', models.BinaryField(blank=True, null=True)),
                ('initiated_by', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
